name: release

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: reviewdog
        uses: reviewdog/action-setup@v1
        run: reviewdog -conf=.reviewdog.yml -reporter=github-pr-check
      - name: build
        env:
          TRAVIS_TAG: ${github.ref_name}
        run: ./scripts/binary.sh darwin && ./scripts/binary.sh windows && ./scripts/binary.sh linux
      - name: update
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/docker-debug-darwin-amd64
            dist/docker-debug-linux-amd64
            dist/docker-debug-windows-amd64.exe
